name: Fixed Login Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行
  workflow_dispatch:

jobs:
  fixed-login:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: Install Chrome and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable chromium-chromedriver
        # 验证安装
        google-chrome --version
        chromedriver --version
        
    - name: System information
      run: |
        echo "=== System Information ==="
        uname -a
        echo "=== Python Information ==="
        python --version
        pip --version
        echo "=== Chrome Information ==="
        google-chrome --version || chromium --version
        echo "=== Selenium Version ==="
        pip show selenium | grep Version
        
    - name: Enhanced environment variable test
      run: |
        echo "=== Enhanced Environment Test ==="
        echo "Current date: $(date)"
        echo ""
        
        # 测试环境变量存在性
        echo "1. Checking if variables exist in shell:"
        if [ -n "$NETLIB_ACCOUNTS" ]; then
            echo "   NETLIB_ACCOUNTS exists (length: ${#NETLIB_ACCOUNTS})"
        else
            echo "   NETLIB_ACCOUNTS does NOT exist"
        fi
        
        if [ -n "$NETLIB_USERNAME" ]; then
            echo "   NETLIB_USERNAME exists"
        else
            echo "   NETLIB_USERNAME does NOT exist"
        fi
        
        echo ""
        echo "2. Python environment check:"
        python -c "import os; print('NETLIB_ACCOUNTS in os.environ:', 'NETLIB_ACCOUNTS' in os.environ)"
        python -c "import os; print('NETLIB_ACCOUNTS length:', len(os.environ.get('NETLIB_ACCOUNTS', '')))"
        python -c "import os; print('NETLIB_ACCOUNTS value preview:', os.environ.get('NETLIB_ACCOUNTS', '')[:20])"
        
        echo ""
        echo "3. Full environment variables (filtered):"
        env | grep -E "(NETLIB_|GITHUB_)" | sort
        
      env:
        NETLIB_ACCOUNTS: ${{ secrets.NETLIB_ACCOUNTS }}
        NETLIB_USERNAME: ${{ secrets.NETLIB_USERNAME }}
        NETLIB_PASSWORD: ${{ secrets.NETLIB_PASSWORD }}
    
    - name: Run fixed login script
      run: |
        python fixed_login.py
      env:
        NETLIB_ACCOUNTS: ${{ secrets.NETLIB_ACCOUNTS }}
        NETLIB_USERNAME: ${{ secrets.NETLIB_USERNAME }}
        NETLIB_PASSWORD: ${{ secrets.NETLIB_PASSWORD }}
        
    - name: Upload all results
      uses: actions/upload-artifact@v4
      with:
        name: fixed-login-results
        path: |
          *.png
          *.log
          *.txt
      if: always()
